// Main = HOME
// 구분자 ==> @GetMapping
// FOOD
export const FETCH_MAIN_DATA='FETCH_MAIN_DATA';
export const FETCH_FOOD_LIST='FETCH_FOOD_LIST';
export const FETCH_FOOD_DETAIL='FETCH_FOOD_DETAIL';
export const FETCH_FOOD_FIND='FETCH_FOOD_FIND';
// SEOUL
export const FETCH_SEOUL_LIST='FETCH_SEOUL_LIST';
export const FETCH_SEOUL_DETAIL='FETCH_SEOUL_DETAIL';
// BOARD
export const FETCH_BOARD_LIST='FETCH_BOARD_LIST';
export const FETCH_BOARD_DETAIL='FETCH_BOARD_DETAIL';
export const FETCH_BOARD_DELETE='FETCH_BOARD_DELETE';
export const FETCH_BOARD_UPDATE='FETCH_BOARD_UPDATE';
export const FETCH_BOARD_UPDATE_OK='FETCH_BOARD_UPDATE_OK';
export const FETCH_BOARD_INSERT='FETCH_BOARD_INSERT';
// NEWS
export const FETCH_NEWS_LIST='FETCH_NEWS_LIST';
// COMMENT
export const FETCH_COMMENT_LIST='FETCH_COMMENT_LIST';
